version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: Add env
          command: |
            echo "WEBSITE_URL=$WEBSITE_URL"> src/.env
            echo "API_URL=API_URL"> src/.env
            echo "FIREBASE_API_KEY=$FIREBASE_API_KEY" >> src/.env
            echo "FIREBASE_AUTH_DOMAIN=$FIREBASE_AUTH_DOMAIN" >> src/.env
            echo "FIREBASE_DATABASE_URL=$FIREBASE_DATABASE_URL" >> src/.env
            echo "FIREBASE_PROJECT_ID=$FIREBASE_PROJECT_ID" >> src/.env
            echo "FIREBASE_STORAGE_BUCKET=$FIREBASE_STORAGE_BUCKET" >> src/.env
            echo "FIREBASE_MESSAGING_SENDER_ID=$FIREBASE_MESSAGING_SENDER_ID" >> src/.env
            echo "FIREBASE_APP_ID=$FIREBASE_APP_ID" >> src/.env
            echo "FIREBASE_MEASUREMENT_ID=$FIREBASE_MEASUREMENT_ID" >> src/.env
      - run:
          name: Install functions dependencies
          command: npm --prefix functions install
      - run:
          name: Install src dependencies
          command: npm --prefix src install
      - run:
          name: build
          command: npm run build
      - run:
          name: deploy to Firebase Hosting
          command: ./src/node_modules/.bin/firebase deploy --project=$FIREBASE_PROJECT_ID --token=$FIREBASE_CI_TOKEN

workflows:
  version: 2
  build_and_test:
    jobs:
      - deploy_dev:
          filters:
            branches:
              only: develop
